sudo: required
language: generic

services:
  - docker

before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - echo $GC_SERVICE_ACC | base64 --decode > service-account.json
  - gcloud components update kubectl
  - glcoud auth activate-service-account --key-file service-account.json
  - gcloud config set project $GC_PROJECT_ID
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials k8s-cluster
  - docker build -t k8s-demo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run k8s-demo/react-test npm test -- --c
