apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-demo-tls
spec:
  secretName: k8s-ssl-domain
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.cloudk8s.fun
  dnsNames:
    - k8s.cloudk8s.fun
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.cloudk8s.fun
