# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: yeasy

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeasy-deployment
  namespace: yeasy
spec:
  replicas: 2
  selector:
    matchLabels:
      component: yeasy-server
  template:
    metadata:
      labels:
        component: yeasy-server
    spec:
      containers:
        - name: yeasy-server
          image: yeasy/simple-web
          ports:
            - containerPort: 80

---
# service
apiVersion: v1
kind: Service
metadata:
  name: yeasy-service
  namespace: yeasy
spec:
  type: ClusterIP
  selector:
    component: yeasy-server
  ports:
    - port: 80
      targetPort: 80

---
# generic-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: generic-ingress-service
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: yeazy.cloudk8s.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yeasy.yeasy-service
                port:
                  number: 80
    - host: html5.cloudk8s.fun
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: html5speed.html5speed-service
                port:
                  number: 80
